const INSTITUTIONS = [
    { isSuperior:false, selectorValue:"CET 1", name:"CET 1 Walter Cross Buchanan"},
    { isSuperior:false, selectorValue:"CECyT 1", name:"CECyT No. 1 Gonzalo Vázquez Vela"},
    { isSuperior:false,selectorValue:"CECyT 2", name:"CECyT No. 2 Miguel Bernard"},
    { isSuperior:false,selectorValue:"CECyT 3", name:"CECyT No. 3 Estanislao Ramírez Ruiz"},
    { isSuperior:false,selectorValue:"CECyT 4", name:"CECyT No. 4 Lázaro Cárdenas"},
    { isSuperior:false,selectorValue:"CECyT 5", name:"CECyT No. 5 Benito Juárez"},
    { isSuperior:false,selectorValue:"CECyT 6", name:"CECyT No. 6 Miguel Othón de Mendizábal"},
    { isSuperior:false,selectorValue:"CECyT 7", name:"CECyT No. 7 Cuauhtémoc"},
    { isSuperior:false,selectorValue:"CECyT 8", name:"CECyT No. 8 Narciso Bassols"},
    { isSuperior:false,selectorValue:"CECyT 9", name:"CECyT No. 9 Juan de Dios Bátiz"},
    { isSuperior:false,selectorValue:"CECyT 10", name:"CECyT No. 10 Carlos Vallejo Márquez"},
    { isSuperior:false,selectorValue:"CECyT 11", name:"CECyT No. 11 Wilfrido Massieu"},
    { isSuperior:false,selectorValue:"CECyT 12", name:"CECyT No. 12 José María Morelos"},
    { isSuperior:false,selectorValue:"CECyT 13", name:"CECyT No. 13 Ricardo Flores Magón"},
    { isSuperior:false,selectorValue:"CECyT 14", name:"CECyT No. 14 Luis Enrique Erro"},
    { isSuperior:false,selectorValue:"CECyT 15", name:"CECyT No. 15 Diódoro Antúnez Echegaray"},
    { isSuperior:true,selectorValue:"CICS Sto Tomas", name:"CICS Unidad Santo Tomás"},
    { isSuperior:true,selectorValue:"CICS Milpa Alta", name:"CICS Unidad Milpa Alta"},
    { isSuperior:true,selectorValue:"ENCB", name:"ENCB"},
    { isSuperior:true,selectorValue:"ENMyH", name:"ENMyH"},
    { isSuperior:true,selectorValue:"ESCA Sto Tomas", name:"ESCA Unidad Santo Tomás"},
    { isSuperior:true,selectorValue:"ESCA Tepepan", name:"ESCA Unidad Tepepan"},
    { isSuperior:true,selectorValue:"ESCOM", name:"ESCOM"},
    { isSuperior:true,selectorValue:"ESE", name:"ESE"},
    { isSuperior:true,selectorValue:"ESEO", name:"ESEO"},
    { isSuperior:true,selectorValue:"ESFM", name:"ESFM"},
    { isSuperior:true,selectorValue:"ESIME Zacatenco", name:"ESIME Unidad Zacatenco"},
    { isSuperior:true,selectorValue:"ESIME Azcapotzalco", name:"ESIME Unidad Azcapotzalco"},
    { isSuperior:true,selectorValue:"ESIME Culhuacan", name:"ESIME Unidad Culhuacán"},
    { isSuperior:true,selectorValue:"ESIME Ticoman", name:"ESIME Unidad Ticomán"},
    { isSuperior:true,selectorValue:"ESIQIE", name:"ESIQIE"},
    { isSuperior:true,selectorValue:"ESIT", name:"ESIT"},
    { isSuperior:true,selectorValue:"ESIA Tecamachalco", name:"ESIA Unidad Tecamachalco"},
    { isSuperior:true,selectorValue:"ESIA Ticoman", name:"ESIA Unidad Ticomán"},
    { isSuperior:true,selectorValue:"ESIA Zacatenco", name:"ESIA Unidad Zacatenco"},
    { isSuperior:true,selectorValue:"ESM", name:"ESM"},
    { isSuperior:true,selectorValue:"EST", name:"EST"},
    { isSuperior:true,selectorValue:"UPIBI", name:"UPIBI"},
    { isSuperior:true,selectorValue:"UPIICSA", name:"UPIICSA"},
    { isSuperior:true,selectorValue:"UPIITA", name:"UPIITA"},
];

module.exports={
    INSTITUTIONS
}